#
# TABLE STRUCTURE FOR: posts
#

DROP TABLE IF EXISTS `posts`;

CREATE TABLE `posts` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `community_id` int(10) unsigned DEFAULT NULL,
  `head` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `body` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `media_id` int(10) unsigned DEFAULT NULL,
  `is_public` tinyint(1) DEFAULT 1,
  `is_archived` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (1, 0, 0, 'in', 'Cumque est sequi in et voluptas. Minima omnis vitae et laborum. Sit non neque error veniam quod repellat. Ut ea rerum nisi iste commodi aperiam commodi rerum.', 0, 1, 1, '2015-06-22 10:28:43', '2012-11-05 00:16:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (2, 0, 0, 'nostrum', 'Aut sunt ipsam nisi ipsa in. Rerum placeat fugit accusantium unde temporibus consectetur qui. Ullam animi sed quo animi eveniet tenetur aut quibusdam. Reprehenderit itaque dolorum quibusdam incidunt. Autem impedit quia dolorem eos rerum sed.', 0, 0, 1, '2020-08-11 12:24:41', '2012-08-24 16:53:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (3, 0, 0, 'minus', 'Illum adipisci id accusantium perspiciatis et. Odit neque unde harum beatae et placeat ut. In nihil placeat assumenda tenetur. Recusandae repellendus ab eos molestiae et occaecati.', 0, 0, 0, '2012-08-11 12:29:10', '2018-08-21 18:17:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (4, 0, 0, 'modi', 'Deserunt eum quisquam eveniet laboriosam consequatur nihil. Qui quod sapiente dolores ducimus odio. Quia sint sunt facilis odio. Asperiores nemo praesentium officiis.', 0, 0, 1, '2011-05-23 02:36:27', '2012-09-14 03:12:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (5, 0, 0, 'laborum', 'Ipsam pariatur ullam qui ut. Omnis eos consequatur non ut excepturi qui aut.', 0, 0, 0, '2017-10-31 18:25:53', '2013-06-02 09:31:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (6, 0, 0, 'voluptas', 'Aut voluptatem est ut enim rerum. Est harum laboriosam eius delectus consequatur quos. Iusto rerum quo enim corrupti illum.', 0, 0, 0, '2018-12-04 00:35:42', '2019-02-19 15:47:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (7, 0, 0, 'dolorum', 'Qui consequatur laborum aliquid ut repudiandae ipsum. Itaque laboriosam quos cumque maxime fuga et dolor ea. Cupiditate impedit distinctio quia aspernatur. Maxime eos quod sint dolor.', 0, 1, 1, '2013-05-12 01:11:47', '2011-05-19 09:16:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (8, 0, 0, 'praesentium', 'Eum sed nihil at commodi asperiores. Nam odio voluptas dolor et nisi. Libero expedita non quae magnam error eaque qui. Possimus aut quos asperiores consequatur quas sunt.', 0, 0, 1, '2019-07-11 15:46:15', '2011-08-03 07:34:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (9, 0, 0, 'quia', 'Officiis natus aut optio eaque aliquam nisi. Libero amet iste error alias omnis.', 0, 1, 0, '2020-12-14 03:02:46', '2011-08-17 09:14:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (10, 0, 0, 'molestias', 'Sed fuga est enim eligendi. Exercitationem rem quasi ex qui voluptatem dolores. Ab soluta ut numquam non explicabo placeat cupiditate.', 0, 0, 0, '2013-01-05 03:13:32', '2013-07-23 05:36:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (11, 0, 0, 'sequi', 'Reiciendis et optio iure doloremque. Accusamus omnis et quidem quia. Velit quia sed consectetur mollitia. Eveniet esse aut doloremque rerum ex.', 0, 0, 1, '2018-06-21 22:30:52', '2012-07-31 03:09:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (12, 0, 0, 'ea', 'Maiores dolorem tempore et et. Neque nulla aspernatur voluptatum laboriosam. Rerum vel dolore consequatur.', 0, 1, 0, '2016-12-23 08:37:50', '2012-04-14 01:41:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (13, 0, 0, 'voluptas', 'Rerum dolorem rem ad assumenda in officiis facilis. Numquam doloremque ducimus iste voluptatem. Laboriosam aut tempora soluta ut.', 0, 1, 1, '2020-12-26 20:39:14', '2014-04-27 07:59:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (14, 0, 0, 'sunt', 'Qui saepe praesentium numquam maxime. Ab doloremque consequatur quia. Vel eos voluptatum dolorum voluptas. Molestiae exercitationem id repellat non est qui.', 0, 0, 0, '2017-01-28 23:48:27', '2018-06-07 10:18:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (15, 0, 0, 'iure', 'Sint vel sit voluptatum quia porro quam libero maxime. Quia praesentium aut sapiente est dolorum cupiditate.', 0, 0, 1, '2011-07-04 07:08:19', '2011-12-25 01:49:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (16, 0, 0, 'natus', 'A aut consequatur dignissimos. Voluptatem cupiditate totam ex et et magnam. Provident hic dolorem repellendus velit qui. Quia et atque ut amet quaerat omnis dolorem recusandae.', 0, 1, 0, '2016-05-01 18:33:23', '2019-07-12 00:53:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (17, 0, 0, 'qui', 'Eos minima maxime laudantium dicta praesentium. Ab facere voluptatem repellat similique excepturi. Maxime sit ratione velit reprehenderit eaque porro ea. Ut saepe in id.', 0, 1, 0, '2012-05-05 09:17:52', '2017-02-06 02:23:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (18, 0, 0, 'culpa', 'Autem itaque assumenda ea numquam sunt necessitatibus et. Recusandae a neque laudantium sed aut neque. Deleniti dicta est nihil eaque quia. Nesciunt cumque mollitia ut.', 0, 0, 1, '2018-02-15 05:12:30', '2014-04-18 02:15:21');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (19, 0, 0, 'eligendi', 'Reprehenderit rerum repudiandae vel odit quidem minima. Id eos impedit delectus quae magni quaerat accusantium. Ratione enim rerum occaecati exercitationem totam. Labore doloremque cumque reiciendis voluptatibus et iste.', 0, 0, 1, '2014-11-22 21:04:10', '2012-08-13 02:19:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (20, 0, 0, 'velit', 'Molestiae iusto est inventore earum distinctio id. Sequi voluptatem necessitatibus quidem consectetur cumque est sed. Dolorem ut doloremque et quis.', 0, 0, 1, '2018-01-04 04:58:26', '2012-09-07 05:18:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (21, 0, 0, 'dicta', 'Odit esse explicabo debitis sit rem ducimus. Qui aliquam eligendi et. Sed est quo saepe sint maxime distinctio voluptas.', 0, 0, 0, '2018-07-01 05:29:49', '2014-03-08 18:14:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (22, 0, 0, 'sed', 'In ea dolores eius sit modi. Nulla expedita tempora enim aut. Inventore pariatur architecto esse veniam ipsa occaecati et. Ea dolorum sequi animi sed qui cumque at.', 0, 1, 0, '2011-08-12 18:13:00', '2017-04-26 23:31:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (23, 0, 0, 'voluptate', 'Modi occaecati est quos saepe. Nulla tempore labore facilis autem ipsum. Enim aut amet porro sit nulla beatae in. Autem natus reprehenderit perferendis vel sint et molestiae enim. Veritatis et officiis distinctio.', 0, 0, 0, '2016-02-19 03:21:16', '2015-08-13 14:56:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (24, 0, 0, 'omnis', 'Itaque ratione fuga voluptatem. Consequatur corrupti et facilis quod et quas voluptatum.', 0, 0, 0, '2012-02-25 21:12:53', '2014-11-18 06:13:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (25, 0, 0, 'adipisci', 'Doloremque et dolore ut aut. Dolore suscipit repudiandae ut possimus. Velit sint non ut ex.', 0, 0, 0, '2017-09-18 05:45:57', '2019-09-13 11:54:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (26, 0, 0, 'dolores', 'Vel magnam quas quidem et nostrum sapiente. Sunt quia consequuntur maxime mollitia eum tempore. Esse nesciunt molestias excepturi quibusdam eos in dolore.', 0, 0, 0, '2019-08-08 10:09:24', '2012-05-25 06:15:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (27, 0, 0, 'delectus', 'Exercitationem veniam amet facilis sequi. Et quas consectetur voluptatibus odit voluptas mollitia. Optio similique natus enim optio rerum porro. Veritatis velit sit pariatur expedita. Cumque possimus est quia vitae.', 0, 0, 0, '2014-11-27 13:56:31', '2011-07-10 21:49:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (28, 0, 0, 'dolor', 'Veritatis ut rerum aperiam corrupti. Animi aut debitis qui qui. Expedita rerum repellat aut dicta.', 0, 1, 0, '2018-04-10 10:12:42', '2019-06-15 09:13:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (29, 0, 0, 'ut', 'Aut dignissimos perspiciatis incidunt reprehenderit. Distinctio eligendi aut accusamus qui beatae exercitationem sunt asperiores. Vero provident numquam cumque qui.', 0, 1, 1, '2019-06-29 11:29:57', '2011-06-06 11:08:27');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (30, 0, 0, 'qui', 'Eaque dicta ad asperiores aut veritatis quae architecto. Placeat laboriosam omnis quidem eius maiores quisquam. Voluptatum reiciendis et blanditiis mollitia rerum qui omnis. Aut sunt explicabo quis dolor.', 0, 1, 1, '2017-12-03 08:29:41', '2020-09-09 18:05:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (31, 0, 0, 'nulla', 'Sunt a aliquam veniam et molestiae. Laborum temporibus autem sapiente magnam animi et. Laborum dolorem natus in laborum dicta eum. Quo sit voluptatem voluptatem sed ut vel.', 0, 1, 1, '2015-05-15 14:31:05', '2019-12-09 11:33:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (32, 0, 0, 'nemo', 'Nostrum eius doloribus quidem aspernatur fugiat nihil. Molestiae quos numquam sunt laborum corrupti porro. Explicabo sed fugit sapiente velit.', 0, 0, 1, '2020-09-21 03:48:03', '2011-10-19 04:48:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (33, 0, 0, 'sequi', 'Quis rem pariatur quam sed. Aut aliquid ullam voluptatem laudantium. Vel aut ab vero tempore deleniti repellendus.', 0, 0, 0, '2018-06-29 13:16:49', '2020-09-17 21:31:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (34, 0, 0, 'deserunt', 'Minima molestias id sit. Minus asperiores sequi corrupti velit. Nihil aut eum consequuntur tempora. Ut consequatur mollitia doloremque aliquam nemo deserunt quo et.', 0, 0, 1, '2016-07-14 14:01:04', '2015-08-02 03:43:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (35, 0, 0, 'laborum', 'Repellat rerum earum nihil vitae. Aut est excepturi odit quos. Ut consequuntur et libero autem. Non sapiente distinctio temporibus quasi voluptatem.', 0, 1, 1, '2011-10-27 04:06:33', '2012-01-05 08:06:55');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (36, 0, 0, 'numquam', 'Aliquid ratione quas voluptas possimus voluptas alias. Harum ea nihil voluptatem doloribus magnam error minima quo. Aut maiores non temporibus facilis totam sed enim. Id quos vel quasi ab nulla quidem.', 0, 0, 0, '2018-04-30 20:29:16', '2019-08-09 03:04:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (37, 0, 0, 'ducimus', 'Asperiores nulla occaecati omnis omnis aliquid hic non. Iure natus voluptatibus dolores aut. Vitae iste aut nam.', 0, 0, 1, '2017-11-17 16:32:28', '2014-01-13 17:16:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (38, 0, 0, 'non', 'Nobis necessitatibus eum est consectetur beatae exercitationem. Dolores voluptas cumque blanditiis debitis quas commodi. In sed nesciunt quia animi provident.', 0, 1, 0, '2016-10-30 07:12:14', '2017-01-14 18:21:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (39, 0, 0, 'necessitatibus', 'A nobis sed voluptatem. Ad perspiciatis odio eligendi. Expedita ad et quasi. Aut et quia inventore et ipsum.', 0, 0, 1, '2016-10-21 16:31:12', '2017-03-05 05:34:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (40, 0, 0, 'et', 'Dolore voluptas voluptatem voluptas quos nesciunt. Consectetur suscipit quidem veniam magnam error perspiciatis. Nihil consequatur et ab velit.', 0, 1, 0, '2014-05-13 23:03:25', '2018-10-16 14:06:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (41, 0, 0, 'nesciunt', 'Possimus pariatur consequatur ipsum fugiat. Et sed optio temporibus culpa fugit voluptas mollitia. Eius velit amet labore. Quibusdam corporis sapiente error.', 0, 0, 0, '2013-05-26 23:20:42', '2018-01-18 18:07:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (42, 0, 0, 'veritatis', 'Nihil enim animi fugit sequi officiis. Vero impedit dolor asperiores ut nemo non. Voluptas dolorem inventore ratione sint unde fugiat unde et. Est corporis perspiciatis voluptas nulla.', 0, 0, 0, '2015-04-26 01:47:39', '2019-09-22 05:51:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (43, 0, 0, 'nemo', 'Deleniti est magnam et blanditiis voluptates ut quasi. Consequuntur laudantium quas voluptatibus qui qui rerum. Iusto placeat ad qui sit quisquam deleniti itaque.', 0, 0, 1, '2015-11-10 05:39:11', '2015-08-16 14:43:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (44, 0, 0, 'porro', 'Magni dolorem pariatur voluptatem quia. Commodi veniam porro sequi sint aspernatur rerum. Omnis et dolor aut omnis architecto quidem.', 0, 1, 0, '2013-04-02 08:07:24', '2016-07-17 14:45:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (45, 0, 0, 'voluptatem', 'Sit eveniet magnam nobis nesciunt voluptates at. Qui sed nobis consequatur mollitia. Repellendus fugiat nihil consequatur maxime et. Provident officia consequatur molestias officiis ut saepe.', 0, 1, 0, '2018-04-22 07:05:24', '2019-03-04 07:19:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (46, 0, 0, 'fuga', 'Harum a quia omnis harum. Eum accusamus est quo similique accusamus accusantium. Perferendis quo labore est numquam.', 0, 1, 1, '2018-05-07 16:36:53', '2014-12-23 02:02:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (47, 0, 0, 'itaque', 'A libero illum impedit suscipit. Amet mollitia nesciunt voluptas. Veritatis doloribus impedit maxime sit. Et placeat reiciendis doloremque porro.', 0, 0, 0, '2011-05-25 15:43:14', '2012-04-26 15:52:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (48, 0, 0, 'ipsam', 'Soluta quo et consequuntur sequi nihil sunt sint. Quisquam cum voluptatibus et omnis non ex aspernatur. Quia harum eaque quia qui dolore.', 0, 0, 0, '2013-05-03 07:28:57', '2019-05-23 14:50:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (49, 0, 0, 'et', 'Omnis iure minima rerum ullam laudantium doloremque. Perferendis quia esse et aliquid ut molestias deleniti. Officiis aliquid nisi eum animi dignissimos eos distinctio voluptatem.', 0, 1, 0, '2012-12-11 21:09:34', '2011-07-05 06:12:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (50, 0, 0, 'fuga', 'Esse et deserunt ut sunt autem earum. Autem ut sequi sed quis velit labore. Tempore et qui sed culpa. Temporibus quibusdam et consequatur ducimus.', 0, 0, 0, '2018-05-11 15:04:46', '2015-09-16 04:53:59');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (51, 0, 0, 'dolorem', 'Reprehenderit et adipisci incidunt voluptatibus. Magni ipsa autem numquam omnis ipsam et pariatur a. In dolorum accusamus ducimus nam.', 0, 0, 1, '2013-10-04 14:03:36', '2012-09-27 22:45:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (52, 0, 0, 'similique', 'Mollitia vel vel qui harum fugiat ratione error reprehenderit. Ducimus nihil aliquam quisquam voluptatem minus qui.', 0, 0, 1, '2015-03-30 09:18:51', '2012-05-08 21:38:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (53, 0, 0, 'quam', 'Est dolorem officiis voluptatem molestias sapiente architecto. Impedit sint suscipit voluptas quia. Aut quaerat dolorum deleniti quisquam error. Delectus nihil consequatur animi exercitationem fugit architecto.', 0, 0, 0, '2015-12-02 14:10:13', '2018-03-29 20:00:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (54, 0, 0, 'veniam', 'Vel eveniet sapiente mollitia blanditiis ipsa ipsam ad magnam. Itaque dolorem blanditiis sequi. Pariatur perferendis voluptatem reiciendis animi vel sequi quia. Explicabo magni adipisci nulla doloremque qui nobis.', 0, 1, 1, '2012-08-04 14:43:00', '2013-10-09 16:51:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (55, 0, 0, 'error', 'Qui ducimus voluptates culpa. Deserunt nulla aut doloribus est soluta praesentium. Et veritatis quaerat facilis quia. Saepe deserunt vitae quo illum. Voluptatem aut id neque assumenda aspernatur.', 0, 0, 0, '2015-04-22 13:39:53', '2019-08-15 09:01:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (56, 0, 0, 'alias', 'Qui doloribus et ratione similique autem id. Earum quam et eum expedita voluptatem. Voluptatem quasi nihil voluptatem porro minus et.', 0, 0, 1, '2011-05-01 08:22:18', '2020-03-01 07:02:20');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (57, 0, 0, 'fugiat', 'Et alias reprehenderit architecto sunt eos dolorem. Autem est eaque assumenda fugiat culpa praesentium.', 0, 1, 0, '2019-10-24 17:48:00', '2014-08-02 02:41:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (58, 0, 0, 'non', 'Quae et impedit aut adipisci suscipit blanditiis suscipit. Itaque saepe quo ratione quae aut molestiae magnam quasi. Beatae ducimus porro beatae ut est aliquid nostrum. Aut repellat quos veritatis dolorem repudiandae. Facilis qui quae ipsa.', 0, 0, 0, '2014-03-12 04:06:19', '2017-01-18 23:42:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (59, 0, 0, 'consequatur', 'Numquam repudiandae sit deleniti ipsam ut non. Quia iure neque aut quis rem. Consequatur eaque dolor quia atque blanditiis a. Ipsum soluta mollitia explicabo officiis.', 0, 0, 1, '2019-02-03 05:07:59', '2018-03-25 18:44:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (60, 0, 0, 'blanditiis', 'Ab sint quam reprehenderit temporibus. Ad porro qui ut. Deleniti qui quod magni temporibus a voluptate porro. Dolore est numquam quia accusamus et animi corporis in.', 0, 0, 0, '2013-03-20 21:58:36', '2020-10-24 21:36:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (61, 0, 0, 'nisi', 'Voluptatibus voluptates minima et dolor. Eius modi voluptatibus ut dolorem voluptas sint. Laborum consequatur incidunt aut deleniti accusantium enim. Non commodi facere veniam.', 0, 0, 1, '2017-11-04 16:06:33', '2020-10-15 09:06:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (62, 0, 0, 'voluptatem', 'Autem veritatis expedita atque reiciendis. Totam dicta iusto eaque quia quibusdam non. Ullam rerum et magni voluptas.', 0, 1, 0, '2019-03-10 01:37:06', '2019-03-25 12:27:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (63, 0, 0, 'dignissimos', 'Rerum consequatur nulla labore dolore aliquam. Dolor consequatur sit velit iste et quia. Provident modi et sunt dolores error qui consequatur.', 0, 0, 0, '2019-10-23 14:24:24', '2015-03-13 05:56:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (64, 0, 0, 'deserunt', 'Quis rerum enim non aliquam. Reiciendis sint nam esse voluptatem enim ad. Occaecati sunt officia excepturi impedit adipisci. Atque officia minus ea quisquam.', 0, 1, 1, '2020-02-18 05:53:16', '2014-03-31 06:50:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (65, 0, 0, 'vel', 'Minima et saepe sint sunt possimus accusantium. Corporis ullam sint expedita sunt sunt voluptatibus. Minus harum tenetur expedita nihil.', 0, 0, 1, '2012-03-28 05:39:02', '2017-12-30 05:19:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (66, 0, 0, 'ad', 'Est exercitationem velit ea distinctio consequuntur qui quidem eos. Excepturi sit omnis sed quaerat ut dolorem quia. Non aperiam doloribus iste consequatur fugiat sunt.', 0, 0, 1, '2011-09-09 13:23:23', '2015-06-01 15:18:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (67, 0, 0, 'amet', 'Sit deserunt repudiandae voluptatibus voluptates. Nisi quasi accusamus occaecati et assumenda voluptatem porro. Magni incidunt quia iure quam. Sit eius commodi nihil doloremque repellendus at quaerat.', 0, 0, 1, '2021-04-13 11:01:05', '2019-08-13 01:15:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (68, 0, 0, 'dicta', 'Nemo ut aspernatur laboriosam cumque. Porro quam molestias voluptatibus molestiae. Quidem non molestiae id ratione cum perspiciatis.', 0, 1, 1, '2020-09-30 15:36:54', '2012-06-05 09:55:45');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (69, 0, 0, 'recusandae', 'Quam cum voluptatem placeat eum eveniet et ut atque. Quo sit repudiandae et quo incidunt exercitationem. Veniam non at vel ipsa. Id eos deserunt similique iure. Ratione error commodi rerum aliquam eaque quisquam.', 0, 1, 1, '2018-06-17 15:06:19', '2019-07-13 08:50:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (70, 0, 0, 'ratione', 'Reprehenderit ducimus veniam omnis et ut. Repellendus facere atque dolor est est reprehenderit et. Quisquam ad esse sed eos.', 0, 0, 0, '2019-04-26 20:09:57', '2011-11-15 02:26:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (71, 0, 0, 'ut', 'Libero illo a dolores consequatur. Dolorem dolor error rerum modi cum. Quisquam consequatur culpa et animi laboriosam maxime. Eos iure eum nihil quos laborum iure.', 0, 1, 0, '2018-10-06 15:50:37', '2020-01-27 06:05:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (72, 0, 0, 'ea', 'Consequatur aut eos excepturi quam. Facere ex voluptate amet atque quia quos. Et quae recusandae et.', 0, 0, 0, '2014-03-05 16:03:03', '2015-08-30 05:20:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (73, 0, 0, 'et', 'Nostrum molestiae officia voluptatem expedita sint et quia. Quis aut sint est necessitatibus atque veniam ea. At rerum deleniti eveniet sapiente temporibus voluptate eaque. Ab accusantium velit perspiciatis officia.', 0, 1, 1, '2011-05-19 05:13:08', '2011-08-06 06:38:17');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (74, 0, 0, 'nam', 'Quia sit et modi id. Et debitis nulla et a. Quas voluptatibus minima quisquam ullam. Velit quo facilis voluptatum impedit quo expedita.', 0, 0, 1, '2017-11-02 18:11:28', '2019-07-03 14:33:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (75, 0, 0, 'dolorem', 'Velit hic ducimus et id ut. Ut ut earum rerum deleniti optio architecto aut. Perspiciatis asperiores qui saepe enim deserunt. Et est nulla quo nulla voluptas quia dolores velit.', 0, 0, 1, '2015-07-05 21:31:44', '2015-05-03 07:42:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (76, 0, 0, 'aliquid', 'Veritatis eaque laboriosam dolorem voluptatum voluptate aut consequatur. Fugiat rerum magnam nisi. Placeat sed ut atque sapiente quisquam odio ea aut. Omnis ut unde est.', 0, 0, 0, '2014-08-17 20:33:50', '2019-06-17 21:42:07');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (77, 0, 0, 'ipsum', 'Ipsam cum porro voluptatum sapiente dolore a aliquid. Voluptatum neque saepe cum et. Dicta consequatur esse quia minima commodi quisquam mollitia.', 0, 0, 1, '2014-05-15 14:54:26', '2018-05-19 01:53:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (78, 0, 0, 'quo', 'Id qui tenetur maxime dolor doloribus praesentium laborum. Sed placeat qui tempora cupiditate officiis nulla vel reprehenderit. Accusamus consequuntur reprehenderit quasi deserunt dolorem. Iure quas voluptatem dolore fugit voluptate ducimus rerum labore.', 0, 1, 1, '2018-06-28 14:22:50', '2013-05-18 12:55:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (79, 0, 0, 'facere', 'Dignissimos soluta sequi cum eligendi. Corporis voluptas quasi odit et et rerum. Eius ducimus ea dicta.', 0, 0, 1, '2014-07-08 10:27:40', '2017-05-12 23:15:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (80, 0, 0, 'quis', 'Animi aut non accusantium iusto modi iusto. Aspernatur consectetur voluptates aperiam maiores dolor enim quasi. Doloribus ut quibusdam eos ab magni voluptatem. Repellat magni blanditiis eum.', 0, 0, 1, '2017-06-14 00:25:47', '2011-09-21 19:46:07');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (81, 0, 0, 'dolores', 'Sunt alias ipsum quia ut rem quam nesciunt. Doloribus porro eligendi officiis quaerat porro aperiam. Sint ipsam dolore accusantium minima praesentium rerum. Ea ea voluptatem eius aperiam.', 0, 0, 0, '2012-06-12 02:47:00', '2015-10-15 00:28:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (82, 0, 0, 'consequatur', 'Optio et delectus quaerat possimus velit. Reiciendis illo in sed autem aspernatur. Nihil itaque ad voluptates.', 0, 0, 1, '2014-12-14 14:18:11', '2012-10-17 22:15:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (83, 0, 0, 'et', 'Incidunt et officia dolor et veritatis voluptatem saepe. Quas aut quia possimus eveniet laudantium omnis nobis. Excepturi ea quia fugiat quia provident nihil. Unde alias commodi placeat ipsum omnis dolores ex.', 0, 1, 0, '2015-05-08 11:16:42', '2015-04-18 00:07:52');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (84, 0, 0, 'error', 'Et harum sunt nulla molestiae. Aut corrupti non necessitatibus. Quia velit rerum quo repellat et aliquam.', 0, 1, 0, '2015-06-19 00:07:56', '2012-07-14 12:23:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (85, 0, 0, 'non', 'Deleniti voluptatibus in fugiat magnam. Atque ut omnis occaecati rerum libero. Totam aut sed fugiat. Quia illo consectetur et maiores. Veniam accusamus neque iure ex voluptatem.', 0, 0, 0, '2017-03-13 00:15:02', '2013-06-25 06:58:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (86, 0, 0, 'aut', 'Facere nihil sit est sed ex. Consequatur et assumenda et et alias. Qui nesciunt architecto aut vitae incidunt non rerum.', 0, 1, 0, '2013-05-16 13:33:16', '2012-04-02 23:51:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (87, 0, 0, 'maxime', 'Officia iure dolorem laboriosam qui enim. Perspiciatis similique voluptatem labore atque ab quo eius.', 0, 0, 1, '2012-02-02 21:09:42', '2021-01-22 14:01:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (88, 0, 0, 'repellat', 'Ipsa aliquam et ratione harum exercitationem dolor quidem qui. Est est ipsam doloribus cupiditate mollitia iste. Sint repellendus veniam consequatur non esse quae et.', 0, 1, 0, '2013-01-02 12:43:12', '2019-02-27 09:18:07');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (89, 0, 0, 'mollitia', 'Nihil eum est iusto veritatis tenetur accusamus. Magnam omnis iusto laborum deleniti. Molestias tempore laudantium qui eum incidunt est nostrum cum.', 0, 0, 0, '2015-07-21 13:29:04', '2013-04-09 08:43:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (90, 0, 0, 'maiores', 'Sunt voluptatibus tenetur quas accusamus. In officia accusamus in quia maiores nesciunt. Nesciunt quia dolores sit velit eos. Sint temporibus facere odio fuga libero eveniet.', 0, 1, 1, '2018-12-24 14:13:40', '2015-02-18 00:05:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (91, 0, 0, 'molestiae', 'Quia ut sit recusandae eaque aut. Suscipit hic quaerat est. Neque officiis repellendus aut quae eveniet ipsam veritatis.', 0, 0, 1, '2014-01-31 04:01:03', '2013-01-17 06:47:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (92, 0, 0, 'labore', 'Distinctio enim autem recusandae tempore quidem. Maxime quo possimus voluptates autem.', 0, 0, 1, '2018-02-24 04:42:53', '2021-03-18 08:32:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (93, 0, 0, 'aut', 'Quaerat quo eius assumenda perferendis aliquid sit. Voluptates aliquam provident dolores quaerat qui. Ut aut aut est quod. Eos provident dicta necessitatibus ut amet et.', 0, 0, 0, '2013-01-15 08:29:25', '2013-01-16 02:06:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (94, 0, 0, 'earum', 'Praesentium nihil non facilis non adipisci nisi eligendi. Totam voluptas magni expedita. Saepe eum voluptas ut sit eaque. Quisquam omnis minima placeat ad corporis sed perferendis.', 0, 0, 1, '2015-11-01 07:56:56', '2016-03-05 08:04:48');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (95, 0, 0, 'qui', 'Facilis sequi autem cum architecto dignissimos voluptatum. Nam ad aspernatur quis non reiciendis quasi sit. Est rerum aliquid qui voluptatibus deserunt accusamus ut. Tenetur nulla nam earum et quod.', 0, 1, 0, '2018-10-23 19:06:23', '2013-01-02 16:53:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (96, 0, 0, 'qui', 'Eaque magnam eum explicabo nam sit error quia. Alias eligendi at expedita inventore non ipsa.', 0, 1, 1, '2015-04-21 12:28:42', '2017-01-31 02:56:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (97, 0, 0, 'illum', 'Ea sunt et animi sed aut officiis. Aut qui odio occaecati ad optio. Necessitatibus voluptas sed ut iusto nulla.', 0, 0, 1, '2019-07-29 04:40:00', '2018-11-09 21:47:22');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (98, 0, 0, 'ut', 'Placeat voluptatem in perferendis repellat. Aperiam unde sed enim quam fuga dolore cumque aut. Asperiores provident quidem et itaque aspernatur similique ut.', 0, 1, 1, '2011-07-23 06:45:50', '2012-04-11 04:15:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (99, 0, 0, 'perspiciatis', 'Repellat iusto vero dolorem ad ut incidunt. Eos aut optio at eum eos. Ab ut numquam est earum placeat facilis voluptatem facere. Eum quasi incidunt nisi asperiores.', 0, 0, 0, '2019-01-14 00:56:02', '2011-06-19 15:52:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (100, 0, 0, 'expedita', 'Consequuntur distinctio officiis et harum. Neque optio voluptatem vel laboriosam voluptatem accusamus. Aliquam impedit porro quos vel quia minus.', 0, 0, 1, '2018-06-13 15:21:33', '2016-02-17 01:11:47');



UPDATE posts SET
  user_id = FLOOR(1 + RAND() * 100),
  community_id = FLOOR(1 + RAND() * 30),
  media_id = FLOOR(1 + RAND() * 150);
 
 SELECT * FROM posts;
