DROP TABLE IF EXISTS artists; 
CREATE TABLE artists (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) COMMENT 'Название артиста',
  country VARCHAR(2) COMMENT 'Страна',
  genre VARCHAR(255) COMMENT 'Жанр',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT = 'Артисты';